{
    'name': 'Hosny POS Controls',
    'version': '19.0.1.16.0',
    'category': 'Point of Sale',
    'summary': 'Zero-tolerance POS controls — audit log, reason codes',
    # pos_modern_ui owns the product card markup this module extends and styles,
    # so it has to be loaded first.
    'depends': ['point_of_sale', 'pos_restaurant', 'pos_loyalty', 'pos_modern_ui'],
    'data': [
        'security/hospitality_security.xml',
        'security/ir.model.access.csv',
        'data/pos_advance_payment_method.xml',
        'views/pos_audit_log_views.xml',
        'views/void_approval_views.xml',
        'views/pos_hospitality_views.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'hosny_pos_controls/static/src/js/odoo19_pos_legacy_compat.js',
            'hosny_pos_controls/static/src/js/odoo19_popup_compat_service.js',
            'hosny_pos_controls/static/src/js/odoo19_model_compat.js',
            'hosny_pos_controls/static/src/js/manager_pin_popup.js',
            'hosny_pos_controls/static/src/js/pos_controls.js',
            'hosny_pos_controls/static/src/js/bill_copies.js',
            'hosny_pos_controls/static/src/js/product_screen_guard.js',
            'hosny_pos_controls/static/src/js/payment_orders_button.js',
            'hosny_pos_controls/static/src/js/payment_orders_screen.js',
            'hosny_pos_controls/static/src/js/hospitality_popup.js',
            'hosny_pos_controls/static/src/js/product_variant_picker.js',
            'hosny_pos_controls/static/src/js/order_expand.js',
            'hosny_pos_controls/static/src/js/qty_entry.js',
            'hosny_pos_controls/static/src/js/void_approval.js',
            'hosny_pos_controls/static/src/xml/controls.xml',
            'hosny_pos_controls/static/src/xml/payment_screen.xml',
            'hosny_pos_controls/static/src/xml/payment_orders.xml',
            'hosny_pos_controls/static/src/xml/product_screen_guard.xml',
            'hosny_pos_controls/static/src/xml/hospitality_popup.xml',
            'hosny_pos_controls/static/src/xml/product_variant_picker.xml',
            # after controls.xml: it extends the orderline head that file builds
            'hosny_pos_controls/static/src/xml/order_expand.xml',
            'hosny_pos_controls/static/src/xml/qty_entry.xml',
            'hosny_pos_controls/static/src/xml/void_approval.xml',
            'hosny_pos_controls/static/src/css/void_approval.css',
            'hosny_pos_controls/static/src/css/controls.css',
            'hosny_pos_controls/static/src/css/orderline_layout.css',
            'hosny_pos_controls/static/src/css/hospitality.css',
            'hosny_pos_controls/static/src/css/product_variant_card_buttons.css',
            'hosny_pos_controls/static/src/css/product_variant_picker.css',
            'pos_modern_ui/static/src/css/pos_responsive_guard.css',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
