{
    'name': 'POS Entry Selector',
    'version': '19.0.2.9.0',
    'license': 'LGPL-3',
    'author': 'Hosney-Pos',
    'depends': ['point_of_sale', 'pos_restaurant', 'pos_modern_ui', 'hosny_pos_printer_matrix'],
    'assets': {
        'point_of_sale._assets_pos': [
            'pos_entry_selector/static/src/js/entry_selector.js',
            'pos_entry_selector/static/src/js/cashier_first.js',
            'pos_entry_selector/static/src/js/takeaway_checkout.js',
            'pos_entry_selector/static/src/js/service_bar.js',
            'pos_entry_selector/static/src/xml/service_bar.xml',
            'pos_entry_selector/static/src/js/table_sort_order.js',
            'pos_entry_selector/static/src/xml/entry_selector.xml',
            'pos_entry_selector/static/src/css/entry_selector.css',
            'pos_entry_selector/static/src/xml/floor_table_ui.xml',
            'pos_entry_selector/static/src/css/floor_table_ui.css',
            'pos_entry_selector/static/src/css/payment_screen_layout.css',
            'pos_entry_selector/static/src/js/hide_quotation_order_button.js',
            'pos_entry_selector/static/src/js/table_number_persistence.js',
            'pos_entry_selector/static/src/js/pos_table_amount.js',
         #   'pos_entry_selector/static/src/js/floor_tone.js',
        ],
    },
    'license': 'LGPL-3',
    'author': 'Hosney-Pos',
    'installable': True,
    'application': False,
}
