{
    "name": "Hosny Purchase Packaging",
    "version": "19.0.6.3.4",
    "category": "Purchases",
    "summary": "Line-level purchase packaging across purchase, stock, and vendor bills",
    "author": "Hosny",
    "license": "LGPL-3",
    "depends": [
        "purchase_stock",
        "account",
        "hosny_purchase_order_line_validation",
        "hosny_stock_branch_location_domain",
        "hosny_purchase_requisition_name",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/purchase_packaging_security.xml",
        "data/packaging_type_data.xml",
        "views/packaging_type_views.xml",
        "views/purchase_packaging_template_views.xml",
        "views/product_views.xml",
        "views/purchase_order_views.xml",
        "views/account_move_views.xml",
        "views/stock_picking_views.xml",
        "wizard/duplicate_purchase_line_warning_views.xml",
        "report/purchase_reports.xml",
        "report/account_reports.xml",
        "report/stock_reports.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hosny_purchase_packaging/static/src/js/purchase_packaging_x2many.js",
            "hosny_purchase_packaging/static/src/js/purchase_packaging_details_button.js",
            "hosny_purchase_packaging/static/src/xml/purchase_packaging_details_button.xml",
            "hosny_purchase_packaging/static/src/scss/purchase_packaging.scss",
        ],
    },
    "installable": True,
    "application": False,
}
